### ISSUE TITLE
Error deploying Container Security 

### ISSUE THREAD

**Issue by GuilhermeHenriSa** [trendmicro/cloudone-container-security-helm#5]
I'm having errors to deploy when the name of namespace is only numbers.

**Comment by zayaanmoez** [comment]
Hi @GuilhermeHenriSa. Are you using Openshift? A fix was released with 2.3.40 for installing the chart with numeric namespaces on Openshift. https://github.com/trendmicro/cloudone-container-security-helm/releases/tag/2.3.40

Please try the latest release to see if it fixes the errors.
